### PR TITLE
Wordblocks

### PR DESCRIPTION
**Pull request by f8daniel**
Took care of all the short-term changes mentioned in #195 
Also: 

1. Discovered and fixed a bug where we don't check if a word fits on the board (overflows to the right or bottom)
2.  Refactored the scoreWord code (renamed scorePlay with a couple subfunctions), cutting 200+ lines of code
3. Tweaked the game loop to report when a player discards tiles and publicly share which tiles are discarded (I don't remember if you get the right of privacy when junking tiles, especially since they don't seem to go back into the deck)

### CODE REVIEW

**Comment by arpee** [comment]
Getting a bug in game play.

1 Create game.
2 Player one plays and word is added.
3 Player two plays across player one's word:

```
Uncaught (in promise) ReferenceError: tmpb is not defined
    at Wordblocks.scoreWord (webpack-internal:///604:2477)
    at Wordblocks.scorePlay (webpack-internal:///604:2529)
    at HTMLSpanElement._callee3$ (webpack-internal:///604:900)
    at tryCatch (webpack-internal:///834:65)
    at Generator.invoke [as _invoke] (webpack-internal:///834:303)
    at Generator.prototype.<computed> [as next] (webpack-internal:///834:117)
    at asyncGeneratorStep (webpack-internal:///604:3)
    at _next (webpack-internal:///604:5)
    ```

**Comment by arpee** [comment]
> Getting a bug in game play.
> 
> 1 Create game.
> 2 Player one plays and word is added.
> 3 Player two plays across player one's word:
> 
> ```
> Uncaught (in promise) ReferenceError: tmpb is not defined
>     at Wordblocks.scoreWord (webpack-internal:///604:2477)
>     at Wordblocks.scorePlay (webpack-internal:///604:2529)
>     at HTMLSpanElement._callee3$ (webpack-internal:///604:900)
>     at tryCatch (webpack-internal:///834:65)
>     at Generator.invoke [as _invoke] (webpack-internal:///834:303)
>     at Generator.prototype.<computed> [as next] (webpack-internal:///834:117)
>     at asyncGeneratorStep (webpack-internal:///604:3)
>     at _next (webpack-internal:///604:5)
> ```

Tested this a little more and it only happens on the first game for a wallet. To replicate the create a new wallet either by resetting in settings or by creating one in a new incognito tab.

**Comment by arpee** [comment]
Aloha,

just checking you saw my note on the small bug I spotted when testing?

r

Richard Parris - Co-Founder

ph : +86 1860 1221 974

**Comment by f8daniel** [comment]
> Tested this a little more and it only happens on the first game for a wallet. To replicate the create a new wallet either by resetting in settings or by creating one in a new incognito tab.

oh, I see that's why I never ran into it. Will fix and push changes asap

**Comment by f8daniel** [comment]
One line of code where the web packer missed a variable name (b/c ambiguous scoping), Fixed and verified by running through a whole game to completion (a first since I don't have the patience for that).

**Comment by arpee** [comment]
All testing out nicely now.

**Pull request merged**
